version: '3.8'

services:
  # Laravel + Vue.js service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alfred-app
    restart: always
    working_dir: /var/www
    expose:
      - "9000"  # Forward port 9000 inside the container to 8000 on your local machine
    environment:
      - APP_ENV=local
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=alfred_db
      - DB_USERNAME=alfred_dev
      - DB_PASSWORD=alfred1234
    depends_on:
      - db
    networks:
      - alfred-network

  # MySQL Database service
  db:
    image: mysql:8.0
    container_name: alfred-db
    environment:
      MYSQL_ROOT_PASSWORD: h4ck2beg0d
      MYSQL_DATABASE: alfred_db
      MYSQL_USER: alfred_dev
      MYSQL_PASSWORD: alfred1234
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - alfred-network

  # Nginx service
  nginx:
    build:
      context: . 
      dockerfile: nginx.Dockerfile
    container_name: alfred-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    depends_on:
      - app
    restart: always
    networks:
      - alfred-network

volumes:
  db_data:

networks:
  alfred-network:
    driver: bridge

