version: '3.8'

services:
  # Laravel + Vue.js service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alfred-app
    restart: always
    working_dir: /var/www
    volumes:
      - ../:/var/www
    ports:
      - "8000:9000"  # Forward port 9000 inside the container to 8000 on your local machine
      - "8080:80"     # Forward port 80 for Nginx to access the Vue.js frontend
    environment:
      - APP_ENV=local
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=alfred_db
      - DB_USERNAME=alfred_dev
      - DB_PASSWORD=alfred_1234
    depends_on:
      - db

  # MySQL Database service
  db:
    image: mysql:8.0
    container_name: alfred-db
    environment:
      MYSQL_ROOT_PASSWORD: h4ck2beg0d
      MYSQL_DATABASE: alfred_db
      MYSQL_USER: alfred_dev
      MYSQL_PASSWORD: alfred1234
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - alfred-network

volumes:
  db_data:

networks:
  alfred-network:
    driver: bridge

